In [1]:
# Import Packages
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# Loading Iris Datasets
iris = sns.load_dataset("iris")

X = iris.iloc[:, :4]  # Input Matrix

In [36]:
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [4]:
y = iris.iloc[:, -1]
y = pd.get_dummies(y)  # Output Matrix
y

setosa  versicolor  virginica
0         1           0          0
1         1           0          0
2         1           0          0
3         1           0          0
4         1           0          0
..      ...         ...        ...
145       0           0          1
146       0           0          1
147       0           0          1
148       0           0          1
149       0           0          1

[150 rows x 3 columns]

In [9]:
def sigmoid(x, w, c):
    return 1 / (1 + np.exp(-(np.dot(x, w) + c)))

In [32]:
x_np = X.to_numpy()[0, :]

In [33]:
x_np

array([5.1, 3.5, 1.4, 0.2])

In [34]:
w

array([[ 0.8760452 , -1.04771945,  1.15571763,  0.7304475 ,  0.73297146],
       [-1.94473448,  1.20519785, -0.26913441, -0.41742535, -0.22592879],
       [-0.76099418,  0.20707567,  0.31108007,  0.28017096, -0.02070319],
       [-0.32555684,  0.96459943, -0.97118624, -1.47781113, -0.47724698]])

In [30]:
x_np[0, :] @ w[:, 0] + c[0]

-4.064875247946272

In [31]:
x_np[0, :] @ w[:, 1] + c[1]

0.20526794555673522

In [37]:
np.dot(x_np, w) + c

array([-4.06487525,  0.20526795,  5.14094092,  2.18163462,  1.94674027])

In [38]:
np.dot(w, x_np) + c

ValueError: shapes (4,5) and (4,) not aligned: 5 (dim 1) != 4 (dim 0)

In [5]:
L = 5  # A number of hidden nodes.
M = X.shape[1]  # A number of features data.
w = np.random.normal(size=(M, L))  # Weight between input matrix and hidden layer.
c = np.random.normal(size=(L))  # bias

In [15]:
X.shape

(150, 4)

In [9]:
w

array([[ 0.8760452 , -1.04771945,  1.15571763,  0.7304475 ,  0.73297146],
       [-1.94473448,  1.20519785, -0.26913441, -0.41742535, -0.22592879],
       [-0.76099418,  0.20707567,  0.31108007,  0.28017096, -0.02070319],
       [-0.32555684,  0.96459943, -0.97118624, -1.47781113, -0.47724698]])

array([-3.46924338, -0.6423509 ,  5.19346433,  2.36097065,  2.82296981])

In [7]:
# Activation
def sigmoid(x, w, c):
    return 1 / (1 + np.exp(-(np.dot(x, w) + c)))


def gaussian(x, w, c):
    return np.exp(-c * np.linalg.norm(x - w, "fro"))


def hyperbolic_tangent(x, w, c):
    return (1 - np.exp(-(np.dot(w, x) + c))) / (1 + np.exp(-(np.dot(x, w) + c)))


# Get function
def getActivation(name):
    return {
        "sigmoid": sigmoid,
        "gaussian": gaussian,
        "hyperbolic_tangent": hyperbolic_tangent,
    }[name]


# Activate function matrix
def H(x, activate, L):
    M = x.shape[1]
    w = np.random.normal(size=(M, L))
    c = np.random.rand(L)
    act = getActivation(activate)
    return act(x, w, c)